### ISSUE TITLE
Check Google Calender typos on Schedule

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#106]
Sometimes the copied text from Word document to the Schedule is missing spaces.
We should check when able to make sure they look ok.

Look out for red squiggles on Google Calender.

**Comment by notshi** [comment]
This could be an ongoing thing @caprenter

**Comment by caprenter** [comment]
I think this is an ongoing thing. It's also not anything we can do much about programmatically (?)
We are paying more attention to the calendar at the moment as we are sing it more, so I think it's ok to close this.
