### ISSUE TITLE
Missing presenters

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#118]
Some presenters are being hidden (put under draft) when they are still very much active.

I know there was a 'cleaning' previously where inactive presenters were 'hidden' from the presenters page but so far, I have found two presenters that are still active (broadcast on international women's day) categorised as 'draft'.

Should I just publish their pages so they are no longer in draft? @caprenter

**Comment by notshi** [comment]
Are we still missing people that should be on the presenter list? I could have sworn Maureen Grant had a page but it seems to be missing and not even in the draft category.

**Comment by caprenter** [comment]
So, yes I think you just re-publish the missing people. I don't think there will be anything in draft that was not previously published. 

There is no system for keeping this page up to date. We currently tend to respond to people that are asking to be added to it.

I feel as though Maureen should have been there - but there is no page that I can see, or picture in the media section, so maybe not?

**Comment by caprenter** [comment]
Saw Maureen at BCB - turns our she has never been on the website. we got a photo and gave her the link to the presenter page

**Comment by notshi** [comment]
Thanks! Yeah, let me know if the photo needs fixing and we can give Maureen a presenter page on the website - there might be some presenters who have presented for a long time without a profile.

**Comment by caprenter** [comment]
There is a plan to get presenters to review their information and to add information about programme pages. I'll close this as this is an ongoing staff process. Again - re-open if you think it needs to stay on this lst
