### ISSUE TITLE
Website Coronavirus update

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#121]
I've added Dom's message to the top of the front page on both mobile and desktop pages.

Mary says this could be updated daily so will have to wait and see for new changes, if there are any.

**Comment by notshi** [comment]
You'll need to update the css when you add extra info on the front section of the website - this should be on lines:

1. https://github.com/caprenter/bcb-website/blob/master/style.css#L562
2. https://github.com/caprenter/bcb-website/blob/master/style.css#L573

Have now fixed it so that you can read the rest of the message by Dom.

**Comment by notshi** [comment]
Updated the mobile site with the new information.

**Comment by caprenter** [comment]
I think we can close this issue as done. New changes can be added as new issues or we can re-open this
