### ISSUE TITLE
Remote support - videos

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#125]
"I think videos might be the way to go (youtube embed)."

**Comment by notshi** [comment]
Would you maybe look at livestreaming as well? Maybe a weekly one during a certain time, mostly as community support to show that the radio is still running as a station, etc. Might be nice to do - but obviously, will take some effort.

**Comment by caprenter** [comment]
I have made a single video about how to use Audacity on YouTube: https://youtu.be/KhWNBMyNy9s using OBStudio and embedded it here:https://www.bcbradio.co.uk/remote-broadcasting/

I can't see us doing a whole load more of this, and as you say it's the time and effort and a clear reason to be doing it. So I'll close this issue

**Comment by notshi** [comment]
@caprenter This is a really great video - could we put it on the front page so it can help members?

Now wondering if there could be a members section on the front page for stuff like BCB Get Together events.
