### ISSUE TITLE
Announcement section on front page 

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#126]
Sorry - I seem to keep messing up this section.

I can see we will need to update it a few more times. Is there a better way of doing this to prevent it getting messed up? 

Do I just need some instructions!

**Comment by notshi** [comment]
Sure thing - I raised it here previously - https://github.com/caprenter/bcb-website/issues/121#issuecomment-601727412

It's been slightly changed from that - 2 steps:

1.Change `style="height:450px;"` for the page to fit.
2. Change [`.home #widgets`](https://github.com/caprenter/bcb-website/blob/master/style.css#L562) ; ie. if the height increased by 50px, add 50px to this `margin-top`.

Hope that makes sense! Let me know if not - sorry, this was a hack to allow full width section over two columns which is the default theme.

**Comment by caprenter** [comment]
That's cool

Thanks
