### ISSUE TITLE
Film image on front page

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#127]
From Rob:
![BCB film image](https://user-images.githubusercontent.com/185467/77518721-2ab62d80-6e76-11ea-8c17-4fc6b325b6eb.jpg)
Given the BCB home page is fairly static, I wondered if a small tweak could make it seem, er.. different!?

The link for the film A Look into Bradford's Community Radio Station is at the top - is there a way to change the still image that links to Youtube?

Even if it's a cropped screen grab with the Youtube link embedded in it? Like the attached (might need title of film overlaid..)?

**Comment by notshi** [comment]
Probably easier to get in touch with Brooke Scaife (Youtube channel owner) and ask her to change the placeholder.

There are some hacks to be able to achieve this but takes some effort. Try the above first?

**Comment by caprenter** [comment]
I think at this point changing the picture would make it look like we have a new video. Unless we have a definite image to use, then I think we should ignore this.
