### ISSUE TITLE
New programme pages have sidebar widget coveriung the page on mobile

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#128]
New programme pages have sidebar widget coveriung the page on mobile

**Comment by caprenter** [comment]
@notshi This is the first commit on this branch that may conflict with what you have been doing on master in terms of css - so perhaps it's time to merge.

Can I go ahead and merge or is there anything more you'd like to commit to master first?

**Comment by notshi** [comment]
Yes, please merge, thanks.

**Comment by notshi** [comment]
Looks ok on the mobile now btw

**Comment by caprenter** [comment]
Thanks -yes fixed and merged somewhere around here 5be02eb128f89168f3bbbd744f2f2fe87e4fc184
