### ISSUE TITLE
Rearrange sidebar

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#137]
The sidebar needs updating due to the current state of things.
What should be prioritised here?

1. I've moved the blog posts further up as they seem to be updated regularly.
2. I've moved the newsletter link further down as there hasn't been a newsletter recently.
3. Are the Women and Girls workshops being done virtually? Otherwise,
    - We should turn this into a International Women's Day link **or**
    - Update the section to include information about what's happening to the workshops.

**Comment by caprenter** [comment]
I've not had any definite information about this. I do know that a Radio Venus show was recorded recently so I think it's worth keeping there as an explicit call out to Women and Girls

So I don't think we need any more action here. Thanks for doing this. Closing
