### ISSUE TITLE
Programme Page images

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#138]
I presenter pages we use the 'built in/theme option' to use the 'Featured Image' 

I think this might be worth following in programme pages in terms of consistency (method and code)

The image is then available in the individual pages and the archive pages to be styled.

I've copied the IT Stuff image into the featured image area, so you can see how that displays by default now. (I've removed it from the main body of the page - I can revert if you like!)

See: IT Stuff here - https://www.bcbradio.co.uk/programmes/ and click through to see it on it's own page.

**Comment by notshi** [comment]
That's cool, thanks. Have gone through and made sure any other programmes with images are now using that.

Also updated the css so that it looks better in the single-programme page.

Could you tell me more about these archive pages? Don't know which are those, thanks!

**Comment by notshi** [comment]
Closing as it's done.
