### ISSUE TITLE
Next On... Last on... Today/Tomorrow/Yesterday with show Descriptions

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#141]
If Next On.. for a programme is 
a) Today (this evening, this afternoon, this morning..)
b) Tomorrow

It might be nice to make the listing say that:
Next on Tonight at 7pm or similar

Similarly, we might say today or Yesterday for last on if it was on recently

We should also be able to add the programme description into these sections.

**Comment by caprenter** [comment]
I've pushed this to the website. Need to look at adding show descriptions still

**Comment by notshi** [comment]
Updated the font-weight as bold for now so it stands out. Have pushed to repo.

**Comment by caprenter** [comment]
this has been out in the wild for a couple of months and seems to be ok. Closing
