### ISSUE TITLE
LGBTQ+ History 2021 - Sidebar Ad

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#158]
We needs a sidebar ad
We don't have any good images yet tho.

Part of #157

**Comment by notshi** [comment]
Had some time to create a logo and ad so have placed a temporary sidebar ad for now.
Would need better copy text, I think - please share with the comms(?) team and let me know?

**Comment by notshi** [comment]
Also, if anyone asks, the font used is from https://www.typewithpride.com/
The font has been included in Adobe Fonts since 2019 under the [SIL Open Font License (OFL) license](https://fonts.adobe.com/variations/43890/eula).

**Comment by caprenter** [comment]
This is great! Thanks ever so much.

I've shared with the team. FYI Jonathan is doing most of the liaison with the group running the month of events in Bradford. He's been asked to direct requests through me, and I'll turn them into tickets.

**Comment by caprenter** [comment]
Sidebar image needs updating - either to images sent via email, or simply to add the Q+ on the graphic you have created.

**Comment by notshi** [comment]
Thanks, @caprenter - some updates:

Updated sidebar image
Still need copy text

**Comment by caprenter** [comment]
Great - thanks for all of this. I'll bring the text issues up today at the staff meeting.

**Comment by caprenter** [comment]
I feel like we can close this now? Re-open if I'm wrong.

**Comment by notshi** [comment]
Thanks, David. 
I'm guessing the current copy text is ok then?

**Comment by caprenter** [comment]
Yeah, unless I'm missing something -I think it's fine!
