### ISSUE TITLE
LGBTQ+ Final program released

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#159]
I've forwarded an email with the info we have from the event organisers.

I think there are a few jobs we 'could' do off the back of that, BUT - I think we can take our time, and choose what we want to do from that email.

There is a logo - we could change the branding we are using, but as you have already done quite a bit of work and may have templates etc, I would not be bothered if we did not use their branding.

No pressure, no expectations, feel free to do as much or as little as you want!

**Comment by notshi** [comment]
Thanks, @caprenter 

I'm going to do a weekly website update, probably on Mondays to keep the workload manageable.

I've decided to use what I've already created - I looked at the lead organiser's Twitter page and they seem happy to promote other designs from Bradford Bantams, University of Bradford; etc.

Also, the branding seems limited for social media posts and doesn't come with a brief that include examples for website placement, typeface download, font sizes and official colours.

Hope that's ok!

By the way, I can include Bradford 2025 and the Council's logo on the web page if needed. They will sit just above the 'Events' section.

**Comment by notshi** [comment]
Added Bradford 2025 and the Council's logos

**Comment by caprenter** [comment]
This seems a very sensible approach - thanks. Weekly is good. We can can get any tasks we feel need doing in issues. 
Anything that needs addressing before a Monday is likely to be text only, and we can (should be able! to) handle that.

Thanks again - all of this is great work, and really appreciated.

**Comment by notshi** [comment]
Looks like Bradford 2025 have created their own branding too using the same font I've picked!
Would be great if BCB started using the banners I've created under the same umbrella.

![Screenshot-20210208163352-626x811](https://user-images.githubusercontent.com/1515961/107249658-77254000-6a2b-11eb-8e4c-63b1fdb52544.png)

https://twitter.com/bradford2025/status/1357017762636263426

**Comment by caprenter** [comment]
"Would be great if BCB started using the banners I've created under the same umbrella."

I'm not sure what you mean here - are you talking about using them on social media?

**Comment by notshi** [comment]
Yep!
