### ISSUE TITLE
Music Blog integration

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#2]
"Music blog is _great_, deserves a skin that lives up to the content"

Could also look at how it integrates with the main site

**Comment by notshi** [comment]
The music blog is updated about once a month - should we move the link from the top navigation bar to the bottom one as the link to the external site directs people away from the main BCB site and that might confuse site users.

**Comment by caprenter** [comment]
I'm pretty sure I agree. I'll try to find out who uses it still. I seem to remember having a chat with someone who does...

**Comment by notshi** [comment]
The link has been moved to the bottom, thank you.
