### ISSUE TITLE
Odd Calendar/Schedule behaviour - Sunday 25th march missing - two Sundays in October

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#37]
Missing from navigation on schedule

**Comment by notshi** [comment]
have a suspicion this is connected to https://github.com/caprenter/bcb-website/issues/36 for some reason - bizarre floating point error in the calendar scheduling script - hopefully i'm wrong!

**Comment by caprenter** [comment]
I have two Sunday 25th Octobers on the Schedule at the moment...
![twoSuns](https://user-images.githubusercontent.com/185467/97000164-437ee280-152e-11eb-9ccd-b0e88d2b2e04.png)

**Comment by caprenter** [comment]
JP wonders if it's something to do with daylight savings....

**Comment by caprenter** [comment]
I think this was to do with daylight savings - made a change in the commit above that seems to fix it
