### ISSUE TITLE
Programme pages

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#4]
Programme pages should be at bcbradio.co.uk/programme/name

A directory of programmes should be available

Probably us a custom post for this

**Comment by caprenter** [comment]
We have the code to do this so should just give it a go..

**Comment by caprenter** [comment]
I'm going to crack on with this in spare time between now and January

**Comment by caprenter** [comment]
This is at a stage now where we can deploy and test it

**Comment by caprenter** [comment]
I've implemented this now, and I'm pretty happy with it - it could do with some better styling if @notshi feels the need for something to do.

Start at https://www.bcbradio.co.uk/programmes/ and click through to individual programmes

Caveats: 
This is still on it's own branch and not merged into master yet. 
Probably needs more real world testing.
The people process to get content in will probably be
1) JE adds data we have in the google calendar
2) Show presenters fill in an online form, the RW edits..

**Comment by notshi** [comment]
Looking good! Will have a go at styling this later today.

**Comment by notshi** [comment]
Should we link programme pages link from Presenter pages to these new pages?

**Comment by notshi** [comment]
Am relative happy with the way it looks now but subject to change @caprenter 

I've added a photo for 10today to show what it could look like on both the single programme page and programme feed if people supplied photos for their programmes.

https://www.bcbradio.co.uk/programmes/10today/

I've tweaked the php functions a bit, mostly to add classes to containers so I can style them.

**Comment by caprenter** [comment]
This is all excellent. I think we can close this issue, and open new issues for further tasks.

I agree that both photos would help, and that we can link presenter pages to programmes. On Presenter pages, programmes are handled via a custom field. I think we can tweak that field in the single presenter page to  easily become a link - will create a new issue for that..
