### ISSUE TITLE
Submenus

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#41]
Recent website discussions are heading the way of having a number of child pages.

I was trying to make 'History' a sub page of 'about' (there may be other discussion about whether or not this is a good thing) - but the styling of such a page is not in line with the rest of the site.

To recreate:
Add the history page to the current menu as a child of 'about' and save the menu and see it in action.

I'd like to see this styled better. I think it's a job for @notshi tho.

**Comment by notshi** [comment]
font-size and style of submenu to replicate main menu
