### ISSUE TITLE
Staff biogs

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#43]
Staff are providing 4 line personal biogs to add to the staff page.

**Comment by notshi** [comment]
Please to be adding technical team biogs as well, not under staff but a separate section.

We are currently invisible but it would be nice to acknowledge that we have helped BCB in some ways.

ie. Spencer, Dick, Richard, yourself and me, etc.

**Comment by caprenter** [comment]
There is a proposal in https://docs.google.com/document/d/1oxKkQdLUlTX2rLQU79VkGEOjWVYUDXSfyjC6wfLb_ZE/edit#
to move all the 'people' to a 'people' section. (including presenters) This would give an consistent place to put tech volunteers.

Like most things BCB, it needs the content. If we can gather it, we have a much better chance of getting it on! (I'd be hap[y to put it under the current man. comm. section if we had the content)

**Comment by notshi** [comment]
Great! That's good to know - will scrounge up some content for people involved and place it when it's done.

@idlemoor @dickthomas

**Comment by notshi** [comment]
will create a new issue for future tech team bio
