### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#44]
Agree on the main menu of the website with [submenus ](https://github.com/caprenter/bcb-website/issues/41) grouped underneath.

With the new pages coming in, it would be good to group them under a main section, ie.

**People**
- *Volunteers*
- *Staff*
- *Management Committee*

**Comment by caprenter** [comment]
We can also have a 

**Projects**

- Radio Venus
- Sounds of the city

**Comment by caprenter** [comment]
I'll create landing pages for both of those top level pages and we'll make people click through twice..

I think wordpress copes with us moving pages about in terms of url redirects

**Comment by caprenter** [comment]
I've created top level pages for projects and people:

http://www.bcbradio.co.uk/projects/
http://www.bcbradio.co.uk/people/

**Comment by notshi** [comment]
http://www.bcbradio.co.uk/people/

We currently have basic links in there to the different pages.

Suggestions:

- These links could be turned into nicer link buttons with images so it's not pure text.
- Add more info about the people of BCB on this page.
