### ISSUE TITLE
Newsletter Updates

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#46]
I think there may be newsletters for April and June that could be added to the website.

**Comment by notshi** [comment]
There are no newsletters for April or June. There is, however, one for May that was posted on the 25th of May (https://mailchi.mp/651c6f2c7c8e/bcb-1066fm-may-2018-newsletter). I'll try to get this done on the 12th as well.

By the way, how does one sign up to get a newsletter? I don't think I signed up for one but they were emailed to me via my @bcbradio account.

**Comment by notshi** [comment]
May newsletter is now live on the website.
