### ISSUE TITLE
caprenter's dev version

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#47]
Get this working!

**Comment by caprenter** [comment]
My only problem was the 'presenter pages'

This is part of the custom code I have written.

The problem was this

WordPress database error Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'bcbradio.wp_postmeta.meta_value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by for query SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  INNER JOIN wp_postmeta ON (wp_posts.ID = wp_postmeta.post_id) WHERE 1=1  AND wp_posts.post_type = 'presenter' AND (wp_posts.post_status = 'publish') AND (wp_postmeta.meta_key = 'surname' ) GROUP BY wp_posts.ID ORDER BY wp_postmeta.meta_value ASC LIMIT 0, 200 made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/responsive-childtheme-master/archive-presenter.php'), query_posts, WP_Query->query, WP_Query->get_posts

It comes from running a newer version of MYSQL

The solutions is to rewrite the SQL, or to disable a default in MYSQL: https://stackoverflow.com/questions/23921117/disable-only-full-group-by

I was unable to successfully rewrite the SQL in a wordpress way - I tried to implement this:
https://codex.wordpress.org/Plugin_API/Filter_Reference/posts_groupby

but failed

**Comment by caprenter** [comment]
Anyway, with the work around I have a working dev version, but this issue may come back to haunt us, so creating it as a new issue

**Comment by caprenter** [comment]
I'm going to have another crack at a dev site to stay up to date with the latest server side software

**Comment by caprenter** [comment]
With wordpress up to date and so on this is now fine

**Comment by notshi** [comment]
This is great news - do you have updated instructions somewhere in docs? @caprenter
