### ISSUE TITLE
Mailchimp integration

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#49]
This is not necessarily - just use the plugin - but a task to investigate the workflow here and make it betterer

**Comment by caprenter** [comment]
We're probably looking at how campaign archives can make it to the page easier - rather than using a plugin to gather contact info. So e.g.:
https://mailchimp.com/help/add-an-email-campaign-archive-to-your-website/
https://wordpress.org/plugins/olalaweb-mailchimp-campaign-manager/

**Comment by notshi** [comment]
Have decided that this is just not possible so will have to, unfortunately, stick with the manual way of doing things. For now, at least - until something new comes up.
