### ISSUE TITLE
Drop downs css

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#51]
It's been reported "in the drop down's on the web site you cant read the options until you hoover over them "
![bcb](https://user-images.githubusercontent.com/185467/41342677-b7451fb4-6ef4-11e8-8b32-95c1ebc49be5.png)

Can you take a look @notshi ? I'm wondering if it's just that his cache needs refreshing?

**Comment by caprenter** [comment]
A refresh on the user side has cleared the css up for them.

I'll see if I can remember how to force a css refresh from wordpress

**Comment by notshi** [comment]
Yeah - that's definitely cache. Could you remove the bug label as well?

Also, does this help -
http://sabrinazeidan.com/force-css-js-refresh-wordpress-development/
