### ISSUE TITLE
August Newsletter

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#58]
We should investigate a better way to integrate the newsletter into the site other than @notshi manually doing this all the time.

this will be part workflow and not just technology. Hopefully Joseph will be available

**Comment by caprenter** [comment]
There is a mailchimp web archive of the news letters:
https://us12.campaign-archive.com/home/?u=25c462ee1f9f3b6ead77f26dc&id=82765425f1

makes me woinder if each of these articles are just 'posts' - but then we need to maybe re-think the newsletter. Lets have a chat next time we meet

**Comment by notshi** [comment]
Have been given access to Mailchimp - will look into redesigning the current template and then have this as an embed to future newsletters.
