### ISSUE TITLE
Broken layout / styles

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#67]
At some point last week (_revision=4714_), the landing page changed.

![screenshot from 2018-10-09 17-08-53](https://user-images.githubusercontent.com/1515961/46682708-2ea0b200-cbe6-11e8-9125-dda03ef951cb.png)

Did we want this new layout?

Am reverting back to the normal layout for now as the text is hard to read. Let me know if the revision was as designed.

**Comment by notshi** [comment]
Twitter broke their own widgets - have updated with their new embed system.

**Comment by notshi** [comment]
![screenshot from 2018-10-09 17-46-15](https://user-images.githubusercontent.com/1515961/46684617-4464a600-cbeb-11e8-8ef2-16f97e533340.png)

- Fixed landing page
- Resized image links
- Changed hover styles for image links
- Fixed Twitter widget

**Comment by caprenter** [comment]
We had this problem again today.
We think it's the visual editor removing span elements, so we've fixed it by adding classes to the span elements so they don't get removed when switching from text view to visual view in the editor

**Comment by notshi** [comment]
Yup - fixed #79
