### ISSUE TITLE
Latest tweet not showing

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#72]
Latest tweets not showing on the home page - it could just be my ad blocker tho...

**Comment by caprenter** [comment]
This is probably not just me, but probably just me - it's about firefox not allowing content that tracks you across sites - I've got this on as a privacy setting.

We might want to look to investigate if there is a way to make people see the content but not be tracked

**Comment by notshi** [comment]
When content blocking is enabled for Firefox, these messages appear in the web console.

![content_warning](https://user-images.githubusercontent.com/1515961/51484221-d5bee900-1d92-11e9-9520-8b80967db7c1.png)

**This is a larger issue about user control and permissions.**

On one hand, it is great that awareness about data protection is up to the user.
On the other hand, non-nefarious site owners and content creators will now have to jump through hoops to get their content displayed.

<hr>

From [twitter](https://twittercommunity.com/t/twitter-widget-being-blocked/85588/7):

> This is expected behaviour. If the Javascript is not able to be loaded, the widget cannot be rendered. This is browser behaviour, and this is not something that we can control.

> You may be able to build something yourself - the widgets that we provide via publish.twitter.com do depend on Javascript, and we do not offer alternatives.

Have looked around and found that the *simplest* (least resistance) way of doing this is by [creating another repo](https://compsci.rocks/embed-twitter-timeline-without-javascript/), embedding it there and adding it as an ```<iframe>``` to the landing page.

<hr>

More info about content blocking and tracking (javascript) can be found [here](https://support.mozilla.org/en-US/kb/content-blocking#w_how-to-detect-when-content-blocking-is-on_2).

![content_blocking](https://user-images.githubusercontent.com/1515961/51484410-6269a700-1d93-11e9-8ac3-4fe615dae945.png)

**Comment by caprenter** [comment]
ok thanks  - I don't think we're going to bother with this. Content blocking is ok in my book. If there's no respectful way round it then lets not
