### ISSUE TITLE
Current project

### ISSUE THREAD

**Issue by caprenter** [caprenter/bcb-website#76]
We talked through the 16 days project and how that should have been on the front page

Look at making a current project box on front page

**Comment by notshi** [comment]
We briefly had a 'This week at BCB' section on the front page but that's no longer the case.

Would be good to have a nicer 'Projects' page than just a bunch of lists.

This could also be somewhat duplicated as a blog post to be randomly displayed on the front page.

**Comment by notshi** [comment]
Closing because raised elsewhere and we now have a proper Projects page - https://www.bcbradio.co.uk/projects/
