### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by notshi** [caprenter/bcb-website#83]
There is always something happening at BCB. It would be nice to know when things are happening or have happened on the website.

For example - BCB Training sessions with Simon Cox.

This is separate from the current/past projects and could have its own section on the side bar before or after the 'radio on air' section.

**Comment by caprenter** [comment]
We should add some literature festival highlights

**Comment by notshi** [comment]
We didn't get to do this today - should we have a page set up for that?
Or will they be populated in "This week in BCB" section on the main page?

**Comment by notshi** [comment]
Closing because raised elsewhere. Also, we seem to have coped by adding these as sidebar widgets or creating an entire project page.
